name: Release Windows Executable
on:
  push:
    tags:
      - '*'

jobs:
  #
  # 1. Build Windows Executable
  #
  build-windows-exe:
    name: 'nicks-script.exe creation using latest python (3.12.6) on Windows'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v2
      # with:
      #   python-version: '3.7'
      # https://hynek.me/articles/python-github-actions/
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install argparse
          pip install pyinstaller==0.17.0 python==3.12
          pip install eel==0.17.0 python==3.12
          pip install cvxpy==1.5.3 python==3.12
          pip install gspread==6.1.2 python==3.12
          pip install mip==1.15.0 python==3.12
          pip install oauth2client==4.1.3 python==3.12
          pip install toml==0.10.2 python==3.12
          python -m eel script.py web --additional-hooks-dir=. --onefile
          mkdir -p target/release
          mv dist/script.exe target/release
      # copy nicks-script.exe to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload nicks-script.exe to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/script.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
